### ISSUE TITLE
must be string or read-only buffer, not None

### ISSUE THREAD

**Issue by twicejr** [Oderik/xbmc-somafm#10]
```
19:02:34 68997.312500 T:1292891120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: must be string or read-only buffer, not None
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.somafm/default.py", line 181, in <module>
                                                build_directory()
                                              File "/home/osmc/.kodi/addons/plugin.audio.somafm/default.py", line 84, in build_directory
                                                xml_data = ET.fromstring(channel_data)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
                                                parser.feed(text)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
                                                self._parser.Parse(data, 0)
                                            TypeError: must be string or read-only buffer, not None
                                            -->End of Python script error report<--
19:02:34 68997.335938 T:1958580784   ERROR: GetDirectory - Error getting plugin://plugin.audio.somafm/
19:02:34 68997.335938 T:1958580784   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.somafm/) failed

```

**Comment by twicejr** [comment]
19:19:30 70013.085938 T:1958580784   ERROR: Control 52 in window 10502 has been asked to focus, but it can't
Might this be of relevance?

**Comment by twicejr** [comment]
`19:23:13 70235.726562 T:1958580784   DEBUG: ------ Window Init (MyMusicNav.xml) ------
19:23:13 70235.726562 T:1958580784   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.somafm/)
19:23:13 70235.726562 T:1958580784   DEBUG:   ParentPath = [plugin://plugin.audio.somafm/]
19:23:13 70235.734375 T:1958580784   DEBUG: StartScript - calling plugin SomaFM('plugin://plugin.audio.somafm/','17','')
19:23:13 70235.734375 T:1343214576   DEBUG: Thread LanguageInvoker start, auto delete: false
19:23:13 70235.734375 T:1958580784   DEBUG: WaitOnScriptResult - waiting on the SomaFM (id=53) plugin...
19:23:13 70235.734375 T:1343214576    INFO: initializing python engine.
19:23:13 70235.734375 T:1343214576   DEBUG: CPythonInvoker(53, /home/osmc/.kodi/addons/plugin.audio.somafm/default.py): start processing
19:23:13 70235.843750 T:1412428784   DEBUG: CAddonDatabase::SetLastUsed[plugin.audio.somafm] took 111 ms
19:23:13 70235.875000 T:1958580784   ERROR: Control 52 in window 10502 has been asked to focus, but it can't
19:23:13 70236.210938 T:1343214576   DEBUG: -->Python Interpreter Initialized<--
19:23:13 70236.210938 T:1343214576   DEBUG: CPythonInvoker(53, /home/osmc/.kodi/addons/plugin.audio.somafm/default.py): the source file to load is "/home/osmc/.kodi/addons/plugin.audio.somafm/default.py"
19:23:13 70236.218750 T:1343214576   DEBUG: CPythonInvoker(53, /home/osmc/.kodi/addons/plugin.audio.somafm/default.py): setting the Python path to /home/osmc/.kodi/addons/plugin.audio.somafm:/home/osmc/.kodi/addons/script.module.beautifulsoup/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
19:23:13 70236.218750 T:1343214576   DEBUG: CPythonInvoker(53, /home/osmc/.kodi/addons/plugin.audio.somafm/default.py): entering source directory /home/osmc/.kodi/addons/plugin.audio.somafm
19:23:13 70236.218750 T:1343214576   DEBUG: CPythonInvoker(53, /home/osmc/.kodi/addons/plugin.audio.somafm/default.py): instantiating addon using automatically obtained id of "plugin.audio.somafm" dependent on version 2.1.0 of the xbmc.python api
19:23:14 70237.171875 T:1343214576   DEBUG: ['plugin://plugin.audio.somafm/', '17', '']
19:23:14 70237.546875 T:1343214576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: must be string or read-only buffer, not None
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.somafm/default.py", line 181, in <module>
                                                build_directory()
                                              File "/home/osmc/.kodi/addons/plugin.audio.somafm/default.py", line 84, in build_directory
                                                xml_data = ET.fromstring(channel_data)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
                                                parser.feed(text)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
                                                self._parser.Parse(data, 0)
                                            TypeError: must be string or read-only buffer, not None
                                            -->End of Python script error report<--
19:23:14 70237.562500 T:1343214576    INFO: Python script stopped
19:23:14 70237.570312 T:1343214576   DEBUG: Thread LanguageInvoker 1343214576 terminating
19:23:14 70237.570312 T:1958580784   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
19:23:14 70237.570312 T:1958580784   ERROR: GetDirectory - Error getting plugin://plugin.audio.somafm/
19:23:14 70237.570312 T:1958580784   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.somafm/) failed
19:23:15 70237.648438 T:1958580784   DEBUG: CGUIMediaWindow::GetDirectory ()
19:23:15 70237.648438 T:1958580784   DEBUG:   ParentPath = [plugin://plugin.audio.somafm/]
19:23:15 70237.718750 T:1958580784   DEBUG: RetrieveMusicInfo() took 0 msec
19:23:15 70237.742188 T:1343214576   DEBUG: Thread BackgroundLoader start, auto delete: false
19:23:15 70237.757812 T:1343214576   DEBUG: Thread BackgroundLoader 1343214576 terminating
19:23:15 70237.867188 T:1958580784   DEBUG: ------ Window Init (DialogNotification.xml) ------
19:23:20 70243.578125 T:1958580784   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
`

**Comment by twicejr** [comment]
Sorry, dude, I think I found the problem: 

                                            Error Contents: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

**Comment by twicejr** [comment]
It's fixed by installing DigiCert CA Certs:
See https://github.com/osmc/osmc/issues/301

**Comment by Oderik** [comment]
Hi! Thanks for investigating! Unfortunately right now I don't have the time to look into it.
